In [2]:

import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


In [3]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[ 0.0180372  -0.02432733 -0.04232268 -0.04277552]
[ 0.01755065  0.17137515 -0.04317819 -0.34850553]
[ 0.02097816  0.36708378 -0.05014831 -0.6544853 ]
[ 0.02831983  0.17269461 -0.06323801 -0.37800555]
[ 0.03177373 -0.0214749  -0.07079812 -0.10591304]
[ 0.03134423 -0.21551462 -0.07291638  0.16362013]
[ 0.02703394 -0.01942869 -0.06964398 -0.15114562]
[ 0.02664536 -0.21348786 -0.07266689  0.11877871]
[ 0.0223756  -0.4074975  -0.07029132  0.38767989]
[ 0.01422565 -0.60155494 -0.06253772  0.65739861]
[ 0.00219456 -0.4056208  -0.04938975  0.34569781]
[-0.00591786 -0.60000667 -0.04247579  0.62240637]
[-0.01791799 -0.79451057 -0.03002767  0.90141495]
[-0.03380821 -0.9892131  -0.01199937  1.18451027]
[-0.05359247 -0.79393756  0.01169084  0.88809032]
[-0.06947122 -0.98921621  0.02945265  1.18442531]
[-0.08925554 -0.79448846  0.05314115  0.90111819]
[-0.10514531 -0.60012524  0.07116352  0.62560107]
[

[-0.01124426  0.54422364 -0.05675714 -0.95381951]
[-3.59784509e-04  3.49909323e-01 -7.58335300e-02 -6.79495026e-01]
[ 0.0066384   0.15591812 -0.08942343 -0.4116182 ]
[ 0.00975676  0.35218641 -0.09765579 -0.73109979]
[ 0.01680049  0.15853995 -0.11227779 -0.47067925]
[ 0.01997129  0.35505391 -0.12169138 -0.79653451]
[ 0.02707237  0.55161683 -0.13762207 -1.12488747]
[ 0.03810471  0.35854029 -0.16011981 -0.87834424]
[ 0.04527551  0.55543332 -0.1776867  -1.21678018]
[ 0.05638418  0.75234481 -0.2020223  -1.55946236]
Episode finished after 13 timesteps
[ 0.04838588  0.00672848  0.03594177 -0.01209064]
[ 0.04852045 -0.18889     0.03569996  0.29171217]
[0.04474265 0.00570522 0.0415342  0.01049889]
[ 0.04485675 -0.18998701  0.04174418  0.31599163]
[ 0.04105701 -0.38567794  0.04806401  0.62154153]
[ 0.03334345 -0.58143697  0.06049484  0.92896634]
[ 0.02171472 -0.7773211   0.07907417  1.24002969]
[ 0.00616829 -0.97336436  0.10387476  1.55639929]
[-0.01329899 -1.16956594  0.13500275  1.87959962]
[-

[-0.00674876  0.55443704 -0.08476459 -1.0069131 ]
[ 0.00433998  0.36054287 -0.10490285 -0.74200703]
[ 0.01155084  0.55694446 -0.11974299 -1.06577481]
[ 0.02268973  0.36359294 -0.14105849 -0.81294468]
[ 0.02996159  0.56033595 -0.15731738 -1.14646185]
[ 0.04116831  0.36757841 -0.18024662 -0.90695682]
[ 0.04851987  0.17529414 -0.19838576 -0.67590909]
Episode finished after 16 timesteps
[ 0.03911991 -0.02275803 -0.02800795  0.02971329]
[ 0.03866475  0.17275414 -0.02741369 -0.27167321]
[ 0.04211983  0.36825632 -0.03284715 -0.57287491]
[ 0.04948496  0.56382306 -0.04430465 -0.87572211]
[ 0.06076142  0.75951835 -0.06181909 -1.1819983 ]
[ 0.07595179  0.95538571 -0.08545906 -1.49340136]
[ 0.0950595   0.7614011  -0.11532708 -1.22858073]
[ 0.11028752  0.95780264 -0.1398987  -1.55505711]
[ 0.12944357  1.15429633 -0.17099984 -1.88791425]
[ 0.1525295   1.35081503 -0.20875813 -2.2284223 ]
Episode finished after 10 timesteps
[-0.04634754 -0.04147423 -0.00852769  0.04138718]
[-0.04717703  0.15376896 -0.

In [4]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)
#> Discrete(2)
print(env.observation_space)
#> Box(4,)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Discrete(2)
Box(4,)


In [5]:
print(env.observation_space.high)
#> array([ 2.4       ,         inf,  0.20943951,         inf])
print(env.observation_space.low)
#> array([-2.4       ,        -inf, -0.20943951,        -inf])

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]
